name: Recaptcha
version: 2.3
description: Protect your Statamic forms using Google's reCAPTCHA service.
url: https://github.com/aryehraber/statamic-recaptcha
developer: Aryeh Raber
developer_url: http://aryehdesigns.com
